version: '3.3'
services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - /nfs-nas-swarm/config/grav:/config
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.grav-http.entrypoints: http
        traefik.http.routers.grav-http.middlewares: https-redirect
        traefik.http.routers.grav-https.tls.certresolver: le
        traefik.http.routers.grav-https.tls: 'true'
        traefik.constraint-label: traefik-public
        traefik.http.routers.grav-https.entrypoints: https
        traefik.http.routers.grav-http.rule: Host(`grav.vnerd.nl`)
        traefik.http.routers.grav-https.rule: Host(`grav.vnerd.nl`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.services.grav.loadbalancer.server.port: '80'
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
