version: '3.3'
services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - /nfs-nas-swarm/config/kavita:/config
     - /media_pool/media:/books
     - /nfs-nas-swarm/data/Books:/Books
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.kavita-http.entrypoints: http
        traefik.http.routers.kavita-http.middlewares: https-redirect
        traefik.http.routers.kavita-https.entrypoints: https
        traefik.http.routers.kavita-http.rule: Host(`books.vnerd.nl`)
        traefik.http.routers.kavita-https.rule: Host(`books.vnerd.nl`)
        traefik.http.routers.kavita-https.tls: 'true'
        traefik.http.routers.kavita-https.tls.certresolver: le
        traefik.constraint-label: traefik-public
        traefik.http.services.kavita.loadbalancer.server.port: '5000'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
