# depricated

version: '3.3'
services:
  adminer:
    image: adminer:4.8.1
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
    - /swarm/config/adminer/settings:/etc/codeproject/adminer
    - /swarm/config/adminer/modules:/app/modules
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 1
      labels:
        traefik.http.routers.adminer-http.rule: Host(`adminer.vnerd.nl`)
        traefik.http.routers.adminer-https.tls.certresolver: le
        traefik.http.routers.adminer-https.tls: 'true'
        traefik.http.services.adminer.loadbalancer.server.port: '8080'
        traefik.http.routers.adminer-http.middlewares: https-redirect
        traefik.http.routers.adminer-https.entrypoints: https
        traefik.http.routers.adminer-https.rule: Host(`adminer.vnerd.nl`)
        traefik.constradminernt-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.adminer-http.entrypoints: http
        traefik.http.routers.adminer-https.middlewares: authelia
      placement:
        constraints:
        # it should work on 386 but no working
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
