version: '3.3'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - jellyfin-config-volume:/config
     - jellyfin-cache-volume:/cache
     - /nfs-nas-swarm/data/media:/media
     - /nfs-nas-swarm/data/autopirate/data:/data
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 0
      labels:
        traefik.http.routers.jellyfin.rule: Host(`jellyfin.vnerd.nl`)
        traefik.http.routers.jellyfin-http.entrypoints: http
        traefik.http.routers.jellyfin-http.middlewares: https-redirect
        traefik.http.services.jellyfin.loadbalancer.server.port: '8096'
        traefik.http.routers.jellyfin-https.tls: 'true'
        traefik.http.routers.jellyfin-https.rule: Host(`jellyfin.vnerd.nl`)
        traefik.constraint-label: traefik-public
        traefik.http.routers.jellyfin-https.entrypoints: https
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.jellyfin-https.tls.certresolver: le
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.hostname == pc03.karam.lab
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
volumes:
  jellyfin-cache-volume:
    driver: local
  jellyfin-config-volume:
    driver: local
