version: '3.3'
services:
  alertmanager:
    image: signoz/alertmanager:0.23.5
    command:
     - --queryService.url=http://query-service:8085
     - --storage.path=/data
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Amsterdam
    volumes:
     - /home/karam/signoz/docker-swarm/clickhouse-setup/data/alertmanager:/data
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.labels.Arch != i686
         - node.labels.worker==enabled
         - node.hostname==pxsw01.karam.lab
  clickhouse:
    image: clickhouse/clickhouse-server:24.1.2-alpine
    healthcheck:
      test:
       - CMD
       - wget
       - --spider
       - -q
       - 0.0.0.0:8123/ping
      interval: 30s
      timeout: 5s
      retries: 3
    tty: true
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Amsterdam
    # ports:
    #   - 9000:9000
    volumes:
     - /home/karam/signoz/docker-swarm/clickhouse-setup/clickhouse-config.xml:/etc/clickhouse-server/config.xml
     - /home/karam/signoz/docker-swarm/clickhouse-setup/clickhouse-users.xml:/etc/clickhouse-server/users.xml
     - /home/karam/signoz/docker-swarm/clickhouse-setup/clickhouse-cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
     - /home/karam/signoz/docker-swarm/clickhouse-setup/data/clickhouse:/var/lib/clickhouse/
    networks:
     - default
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 50m
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.labels.Arch != i686
         - node.labels.worker==enabled
         - node.hostname==pxsw01.karam.lab
  frontend:
    image: signoz/frontend:0.45.0
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Amsterdam
    ports:
     - 3301:3301
    volumes:
     - /home/karam/signoz/docker-swarm/common/nginx-config.conf:/etc/nginx/conf.d/default.conf
    networks:
     - default
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.signoz-https.entrypoints: https
        traefik.http.routers.signoz-http.rule: Host(`signoz.vnerd.nl`)
        traefik.http.routers.signoz-https.rule: Host(`signoz.vnerd.nl`)
        traefik.http.routers.signoz-http.middlewares: https-redirect
        traefik.constraint-label: traefik-public
        traefik.http.services.signoz.loadbalancer.server.port: '3301'
        traefik.http.routers.signoz-https.tls: 'true'
        traefik.http.routers.signoz-http.entrypoints: http
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.signoz-https.tls.certresolver: le
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.labels.Arch != i686
         - node.labels.worker==enabled
         - node.hostname==pxsw01.karam.lab
  hotrod:
    image: jaegertracing/example-hotrod:1.30
    command:
     - all
    environment:
      JAEGER_ENDPOINT: http://otel-collector:14268/api/traces
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Amsterdam
    networks:
     - default
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 50m
    deploy:
      placement:
        constraints:
         - node.labels.Arch != i686
         - node.labels.worker==enabled
         - node.hostname==pxsw01.karam.lab
  load-hotrod:
    image: signoz/locust:1.2.3
    environment:
      ATTACKED_HOST: http://hotrod:8080
      LOCUST_MODE: standalone
      LOCUST_OPTS: --headless -u 10 -r 1
      NO_PROXY: standalone
      PGID: '1000'
      PUID: '1000'
      QUIET_MODE: 'false'
      TASK_DELAY_FROM: '5'
      TASK_DELAY_TO: '30'
      TZ: Europe/Amsterdam
    volumes:
     - /home/karam/signoz/docker-swarm/common/locust-scripts:/locust
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.labels.Arch != i686
         - node.labels.worker==enabled
         - node.hostname==pxsw01.karam.lab
  logspout:
    image: gliderlabs/logspout:v3.2.14
    command:
     - syslog+tcp://otel-collector:2255
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Amsterdam
    volumes:
     - /etc/hostname:/etc/host_hostname:ro
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.labels.Arch != i686
         - node.labels.worker==enabled
         - node.hostname==pxsw01.karam.lab
  otel-collector:
    image: signoz/signoz-otel-collector:0.88.22
    command:
     - --config=/etc/otel-collector-config.yaml
     - --manager-config=/etc/manager-config.yaml
     - --feature-gates=-pkg.translator.prometheus.NormalizeName
    user: root
    environment:
      DOCKER_MULTI_NODE_CLUSTER: 'false'
      LOW_CARDINAL_EXCEPTION_GROUPING: 'false'
      # OTEL_RESOURCE_ATTRIBUTES: host.name={{.Node.Hostname}},os.type={{.Node.Platform.OS}},dockerswarm.service.name={{.Service.Name}},dockerswarm.task.name={{.Task.Name}}
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Amsterdam
    ports:
     # - 1777:1777     # pprof extension
     - 4317:4317
     - 4318:4318
     # - 8888:8888     # OtelCollector internal metrics
     # - 8889:8889     # signoz spanmetrics exposed by the agent
     # - 9411:9411     # Zipkin port
     # - 13133:13133   # Health check extension
     # - 14250:14250   # Jaeger gRPC
     # - 14268:14268   # Jaeger thrift HTTP
     # - 55678:55678   # OpenCensus receiver
     # - 55679:55679   # zPages extension
    volumes:
     - /home/karam/signoz/docker-swarm/clickhouse-setup/otel-collector-config.yaml:/etc/otel-collector-config.yaml
     - /home/karam/signoz/docker-swarm/clickhouse-setup/otel-collector-opamp-config.yaml:/etc/manager-config.yaml
     - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.labels.Arch != i686
         - node.labels.worker==enabled
         - node.hostname==pxsw01.karam.lab
  otel-collector-migrator:
    image: signoz/signoz-schema-migrator:0.88.22
    command:
     - --dsn=tcp://clickhouse:9000
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Amsterdam
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.labels.Arch != i686
         - node.labels.worker==enabled
         - node.hostname==pxsw01.karam.lab
  query-service:
    image: signoz/query-service:0.45.0
    command:
     - -config=/root/config/prometheus.yml
    healthcheck:
      test:
       - CMD
       - wget
       - --spider
       - -q
       - localhost:8080/api/v1/health
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      ALERTMANAGER_API_PREFIX: http://alertmanager:9093/api/
      ClickHouseUrl: tcp://clickhouse:9000
      DASHBOARDS_PATH: /root/config/dashboards
      DEPLOYMENT_TYPE: docker-swarm
      GODEBUG: netdns=go
      PGID: '1000'
      PUID: '1000'
      SIGNOZ_LOCAL_DB_PATH: /var/lib/signoz/signoz.db
      STORAGE: clickhouse
      TELEMETRY_ENABLED: 'true'
      TZ: Europe/Amsterdam
    volumes:
     - /home/karam/signoz/docker-swarm/clickhouse-setup/prometheus.yml:/root/config/prometheus.yml
     - /home/karam/signoz/docker-swarm/dashboards:/root/config/dashboards
     - /home/karam/signoz/docker-swarm/clickhouse-setup/data/signoz:/var/lib/signoz/
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
         - node.labels.Arch != i686
         - node.labels.worker==enabled
         - node.hostname==pxsw01.karam.lab
  zookeeper-1:
    image: bitnami/zookeeper:3.7.1
    user: root
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Amsterdam
      ZOO_AUTOPURGE_INTERVAL: '1'
      ZOO_SERVER_ID: '1'
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    volumes:
     - /home/karam/signoz/docker-swarm/clickhouse-setup/data/zookeeper-1:/bitnami/zookeeper
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.labels.Arch != i686
         - node.labels.worker==enabled
         - node.hostname==pxsw01.karam.lab
networks:
  default:
    driver: overlay
  traefik-public:
    external: true
