version: '3.3'
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - /nfs-nas-swarm/data/audiobookshelf/audiobooks:/audiobooks
     - /nfs-nas-swarm/data/audiobookshelf/podcasts:/podcasts
     - /nfs-nas-swarm/config/audiobookshelf:/config
     - /nfs-nas-swarm/data/audiobookshelf/metadata:/metadata
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.audiobookshelf-https.rule: Host(`audiobookshelf.vnerd.nl`)
        traefik.http.routers.audiobookshelf-http.middlewares: https-redirect
        traefik.http.services.audiobookshelf.loadbalancer.server.port: '80'
        traefik.http.routers.audiobookshelf-https.tls: 'true'
        traefik.http.routers.audiobookshelf-http.entrypoints: http
        traefik.http.routers.audiobookshelf-https.tls.certresolver: le
        traefik.constraint-label: traefik-public
        traefik.http.routers.audiobookshelf-https.entrypoints: https
        traefik.http.routers.audiobookshelf-http.rule: Host(`audiobookshelf.vnerd.nl`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
