version: '3.3'
services:
  authelia:
    image: authelia/authelia:4.38.0
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - /swarm/config/authelia:/config
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.authelia-https.tls: 'true'
        traefik.http.routers.authelia-https.tls.certresolver: le
        traefik.http.services.authelia.loadbalancer.server.port: '9091'
        traefik.http.routers.authelia-http.middlewares: https-redirect
        traefik.http.middlewares.authelia.forwardAuth.address: http://authelia:9091/api/verify?rd=https%3A%2F%2Fauthelia.vnerd.nl%2F
        traefik.http.routers.authelia-https.rule: Host(`authelia.vnerd.nl`)
        traefik.http.routers.authelia-http.rule: Host(`authelia.vnerd.nl`)
        traefik.http.routers.authelia-https.entryPoints: https
        traefik.constraint-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.authelia-http.entryPoints: http
      placement:
        constraints:
         - node.labels.Arch != i686
         - node.labels.worker==enabled
  whoami-1fa:
    image: containous/whoami:latest
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 0
      labels:
        traefik.http.routers.whoami-authelia-1fa-https.rule: Host(`whoami-authelia-1fa.vnerd.nl`)
        traefik.http.routers.whoami-authelia-1fa-http.entrypoints: http
        traefik.http.routers.whoami-authelia-1fa-http.middlewares: authelia
        traefik.http.routers.whoami-authelia-1fa-https.entrypoints: https
        traefik.http.routers.whoami-authelia-1fa-https.tls.certresolver: le
        traefik.http.routers.whoami-authelia-1fa-https.tls: 'true'
        traefik.constraint-label: traefik-public
        traefik.http.routers.whoami-authelia-1fa-https.middlewares: authelia
        traefik.http.services.whoami-authelia-1fa.loadbalancer.server.port: '80'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.whoami-authelia-1fa-http.rule: Host(`whoami-authelia-1fa.vnerd.nl`)
  whoami-2fa:
    image: containous/whoami:latest
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 0
      labels:
        traefik.http.routers.whoami-authelia-2fa-http.entrypoints: http
        traefik.http.routers.whoami-authelia-2fa-https.middlewares: authelia
        traefik.http.routers.whoami-authelia-2fa-http.rule: Host(`whoami-authelia-2fa.vnerd.nl`)
        traefik.http.routers.whoami-authelia-2fa-https.tls.certresolver: le
        traefik.http.routers.whoami-authelia-2fa-https.tls: 'true'
        traefik.http.routers.whoami-authelia-2fa-http.middlewares: authelia
        traefik.constraint-label: traefik-public
        traefik.http.services.whoami-authelia-2fa.loadbalancer.server.port: '80'
        traefik.http.routers.whoami-authelia-2fa-https.entrypoints: https
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.whoami-authelia-2fa-https.rule: Host(`whoami-authelia-2fa.vnerd.nl`)
networks:
  traefik-public:
    external: true
