version: '3.3'
services:
  cv:
    image: nginx:latest
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - /swarm/data/CV:/usr/share/nginx/html
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.cv-http.middlewares: https-redirect
        traefik.http.routers.cv-http.rule: Host(`cv.vnerd.nl`)
        traefik.http.services.cv.loadbalancer.server.port: '80'
        traefik.http.routers.cv-https.tls: 'true'
        traefik.http.routers.cv-https.tls.certresolver: le
        traefik.constraint-label: traefik-public
        traefik.http.routers.cv-https.rule: Host(`cv.vnerd.nl`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.cv-https.entrypoints: https
        traefik.http.routers.cv-http.entrypoints: http
      placement:
       constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  traefik-public:
    external: true
