version: '3.3'
services:
  cyberchef:
    image: mpepping/cyberchef:v10.18.3
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 0
      labels:
        sablier.enable: 'true'
        traefik.http.services.cyberchef.loadbalancer.server.port: '8000'
        traefik.http.routers.cyberchef-https.rule: Host(`cyberchef.vnerd.nl`)
        traefik.http.routers.cyberchef-https.tls: 'true'
        traefik.http.routers.cyberchef-http.rule: Host(`cyberchef.vnerd.nl`)
        traefik.http.routers.cyberchef-https.entrypoints: https
        traefik.http.routers.cyberchef-https.tls.certresolver: le
        sablier.group: cyberchef
        traefik.constraint-label: traefik-public
        traefik.docker.lbswarm: 'true'
        traefik.http.routers.cyberchef-http.entrypoints: http
        traefik.http.routers.cyberchef-http.middlewares: https-redirect
        traefik.http.routers.cyberchef-https.middlewares: cyberchef-sablier@file
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  traefik-public:
    external: true