version: '3.3'
services:
  dashpc01:
    image: mauricenino/dashdot:5.7.0
    environment:
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_CPU_TEMPS_MODE: avg
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      PGID: '911'
      PUID: '911'
    volumes:
     - /:/mnt/host:ro
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.dashpc01-https.rule: Host(`dashpc01.vnerd.nl`)
        traefik.http.services.dashpc01.loadbalancer.server.port: '3001'
        traefik.http.routers.dashpc01-http.entrypoints: http
        traefik.http.routers.dashpc01-https.tls.certresolver: le
        traefik.constraint-label: traefik-public
        traefik.http.routers.dashpc01-https.entrypoints: https
        traefik.http.routers.dashpc01-http.rule: Host(`dashpc01.vnerd.nl`)
        traefik.http.routers.dashpc01-https.tls: 'true'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.dashpc01-http.middlewares: https-redirect
      placement:
        constraints:
         - node.hostname==pc01.karam.lab
  dashpx01:
    image: mauricenino/dashdot:5.7.0
    environment:
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_CPU_TEMPS_MODE: avg
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      PGID: '911'
      PUID: '911'
    volumes:
     - /:/mnt/host:ro
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.dashpxsw01-https.entrypoints: https
        traefik.http.routers.dashpxsw01-http.rule: Host(`dashpx01.vnerd.nl`)
        traefik.http.routers.dashpxsw01-http.entrypoints: http
        traefik.http.services.dashpxsw01.loadbalancer.server.port: '3001'
        traefik.http.routers.dashpxsw01-https.rule: Host(`dashpx01.vnerd.nl`)
        traefik.http.routers.dashpxsw01-http.middlewares: https-redirect
        traefik.constraint-label: traefik-public
        traefik.http.routers.dashpxsw01-https.tls: 'true'
        traefik.http.routers.dashpxsw01-https.tls.certresolver: le
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.hostname==px01
  dashpx02:
    image: mauricenino/dashdot:5.7.0
    environment:
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_CPU_TEMPS_MODE: avg
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      PGID: '911'
      PUID: '911'
    volumes:
     - /:/mnt/host:ro
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.dashpxsw02-http.middlewares: https-redirect
        traefik.http.routers.dashpxsw02-http.rule: Host(`dashpx02.vnerd.nl`)
        traefik.http.services.dashpxsw02.loadbalancer.server.port: '3001'
        traefik.http.routers.dashpxsw02-https.entrypoints: https
        traefik.http.routers.dashpxsw02-https.tls.certresolver: le
        traefik.constraint-label: traefik-public
        traefik.http.routers.dashpxsw02-http.entrypoints: http
        traefik.http.routers.dashpxsw02-https.tls: 'true'
        traefik.http.routers.dashpxsw02-https.rule: Host(`dashpx02.vnerd.nl`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.hostname==px02
  dashpx03:
    image: mauricenino/dashdot:5.7.0
    environment:
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_CPU_TEMPS_MODE: avg
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      PGID: '911'
      PUID: '911'
    volumes:
     - /:/mnt/host:ro
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.dashpxsw03-https.tls.certresolver: le
        traefik.http.routers.dashpxsw03-http.entrypoints: http
        traefik.http.routers.dashpxsw03-https.tls: 'true'
        traefik.http.routers.dashpxsw03-https.entrypoints: https
        traefik.constraint-label: traefik-public
        traefik.http.routers.dashpxsw03-http.middlewares: https-redirect
        traefik.http.routers.dashpxsw03-https.rule: Host(`dashpx03.vnerd.nl`)
        traefik.http.services.dashpxsw03.loadbalancer.server.port: '3001'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.dashpxsw03-http.rule: Host(`dashpx03.vnerd.nl`)
      placement:
        constraints:
         - node.hostname==px03
  dashpxsw04:
    image: mauricenino/dashdot:5.7.0
    environment:
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
      DASHDOT_CPU_TEMPS_MODE: avg
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      PGID: '911'
      PUID: '911'
    volumes:
     - /:/mnt/host:ro
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.services.dashpxsw04.loadbalancer.server.port: '3001'
        traefik.http.routers.dashpxsw04-https.rule: Host(`dashpxsw04.vnerd.nl`)
        traefik.http.routers.dashpxsw04-http.rule: Host(`dashpxsw04.vnerd.nl`)
        traefik.http.routers.dashpxsw04-http.entrypoints: http
        traefik.http.routers.dashpxsw04-http.middlewares: https-redirect
        traefik.http.routers.dashpxsw04-https.entrypoints: https
        traefik.constraint-label: traefik-public
        traefik.http.routers.dashpxsw04-https.tls: 'true'
        traefik.http.routers.dashpxsw04-https.tls.certresolver: le
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.hostname==pxsw04.karam.lab
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
