version: '3.3'
services:
  diskover:
    image: lscr.io/linuxserver/diskover:latest
    # command:
      # - python3 /app/diskover/diskover.py -f -i diskover-nfs-nas-swarm /nfs-nas-swarm
    #  - /bin/bash
    #  - -c
      # - crontab /config/crontabs/abc
    environment:
      ES_HOST: elasticsearch
      ES_PASS: changeme
      ES_PORT: '9200'
      ES_USER: elastic
      PGID: '1000'
      PUID: '1000'
    volumes:
     - /nfs-nas-swarm/config/diskover/diskover:/config
     - /nfs-nas-swarm:/nfs-nas-swarm
     - /media_pool:/media_pool
     - /media_services_config:/media_services_config
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.diskover-https.entrypoints: https
        traefik.http.routers.diskover-https.tls.certresolver: le
        traefik.http.routers.diskover-http.middlewares: https-redirect
        traefik.http.services.diskover.loadbalancer.server.port: '80'
        traefik.http.routers.diskover-https.rule: Host(`diskover.vnerd.nl`)
        traefik.constraint-label: traefik-public
        traefik.http.routers.diskover-https.tls: 'true'
        traefik.http.routers.diskover-http.entrypoints: http
        traefik.http.routers.diskover-https.middlewares: authelia
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.diskover-http.rule: Host(`diskover.vnerd.nl`)
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      PGID: '1000'
      PUID: '1000'
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      xpack.security.enabled: 'false'
    ports:
     - 9200:9200
    volumes:
     - /nfs-nas-swarm/data/diskover/esdata:/usr/share/elasticsearch/data
    networks:
     - internal
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
  elasticsearch-helper:
    image: alpine:latest
    command:
     - sh
     - -c
     - sysctl -w vm.max_map_count=262144
    environment:
      PGID: '0'
      PUID: '0'
    networks:
     - internal
    logging:
      driver: json-file
    deploy:
      replicas: 0
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
