version: '3.3'
services:
  docs:
    image: keinstien/mkdocs-material:9.5.2
    environment:
      FAST_MODE: 'true'
      LIVE_RELOAD_SUPPORT: 'true'
      PGID: '0'
      PUID: '0'
      TZ: Europe/Amsterdam
    volumes:
     - /nfs-nas-swarm/config/docs:/docs
     - /nfs-nas-swarm/github-repos/portainer-compose:/docs/github-repos/portainer-compose
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      # replicas: 0
      labels:
        # sablier.enable: 'true'
        traefik.http.routers.docs-https.tls: 'true'
        traefik.http.routers.docs-https.tls.certresolver: le
        traefik.http.routers.docs-http.entrypoints: http
        traefik.http.services.docs.loadbalancer.server.port: '8000'
        # traefik.http.routers.docs-https.middlewares: docs-sablier@file
        # traefik.http.routers.docs-https.middlewares: 500error@file
        traefik.http.routers.docs-https.entrypoints: https
        traefik.http.routers.docs-https.rule: Host(`docs.vnerd.nl`)
        # sablier.group: docs
        traefik.constraint-label: traefik-public
        # traefik.docker.lbswarm: 'true'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.docs-http.middlewares: https-redirect
        traefik.http.routers.docs-http.rule: Host(`docs.vnerd.nl`)
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
