version: '3.3'
services:
  ha:
    image: homeassistant/home-assistant:2025.8
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Amsterdam
    volumes:
     - /swarm/config/ha:/config
    #  - /nfs-nas-swarm:/nas-parent-dir
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - outside
    #  - traefik-public
    ports:
     - 8123:8123
    #  - target: 8123
    #    host_ip: 10.10.10.27
    #    published: 8122
    #    protocol: tcp
    #    mode: host
    logging:
      driver: json-file
    deploy:
      # labels:
      #   traefik.http.routers.ha-http.middlewares: https-redirect
      #   traefik.http.routers.ha-https.rule: Host(`ha.vnerd.nl`)
      #   traefik.http.routers.ha-https.tls.certresolver: le
      #   traefik.http.routers.ha-http.entrypoints: http
      #   traefik.http.routers.ha-https.tls: 'true'
      #   traefik.http.routers.ha-http.rule: Host(`ha.vnerd.nl`)
      #   traefik.constraint-label: traefik-public
      #   traefik.http.services.ha.loadbalancer.server.port: '8123'
      #   traefik.docker.network: traefik-public
      #   traefik.enable: 'true'
      #   traefik.http.routers.ha-https.entrypoints: https
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  outside:
    external:
      name: "host"
  # traefik-public:
  #   external: true
