version: '3.3'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    volumes:
     - /nfs-nas-swarm/config/homeassistant:/config
     - /nfs-nas-swarm:/nas-parent-dir
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.homeassistant-http.middlewares: https-redirect
        traefik.http.routers.homeassistant-https.rule: Host(`homeassistant.vnerd.nl`)
        traefik.http.routers.homeassistant-https.tls.certresolver: le
        traefik.http.routers.homeassistant-http.entrypoints: http
        traefik.http.routers.homeassistant-https.tls: 'true'
        traefik.http.routers.homeassistant-http.rule: Host(`homeassistant.vnerd.nl`)
        traefik.constraint-label: traefik-public
        traefik.http.services.homeassistant.loadbalancer.server.port: '8123'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.homeassistant-https.entrypoints: https
      placement:
        constraints:
         - node.labels.Arch != i686
networks:
  internal:
    external: true
  traefik-public:
    external: true
