version: '3.3'

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v1.138.0
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
      DB_PASSWORD: "password"
      DB_USERNAME: "postgres"
      DB_DATABASE_NAME: "immich"
      UPLOAD_LOCATION: "/swarm/data/immich"
    volumes:
      - /nfs-nas-swarm/data/immich:/data
      - /etc/localtime:/etc/localtime:ro
      - /nas_files:/nas_files
      - /photos/BackupKoki:/photos/BackupKoki
      - /photos/BackupSanaa:/photos/BackupSanaa
      - /photos/BackupLama:/photos/BackupLama
    networks:
      - internal
      - traefik-public
    depends_on:
      - redis
      - database
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.services.immich.loadbalancer.server.port: '2283'
        traefik.http.routers.immich-http.rule: Host(`immich.vnerd.nl`)
        traefik.http.routers.immich-http.entrypoints: http
        traefik.http.routers.immich-http.middlewares: https-redirect
        traefik.http.routers.immich-https.rule: Host(`immich.vnerd.nl`)
        traefik.http.routers.immich-https.entrypoints: https
        traefik.http.routers.immich-https.tls: 'true'
        traefik.http.routers.immich-https.tls.certresolver: le
        # traefik.http.routers.immich-https.middlewares: authelia
        traefik.constraint-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
          - node.labels.Arch!=i686
          - node.labels.worker==enabled

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.138.0
    environment:
      PGID: '911'
      PUID: '911'
    volumes:
      - /swarm/config/immich/cache:/cache
    networks:
      - internal
      - traefik-public
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.labels.Arch!=i686
          - node.labels.worker==enabled

  redis:
    image: docker.io/valkey/valkey:8-bookworm@sha256:facc1d2c3462975c34e10fccb167bfa92b0e0dbd992fc282c29a61c3243afb11
    command: redis-server --appendonly yes
    networks:
      - internal
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.labels.Arch!=i686
          - node.labels.worker==enabled

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "immich"
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /swarm/config/immich/db:/var/lib/postgresql/data
    shm_size: 128mb
    networks:
      - internal
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.labels.Arch!=i686
          - node.labels.worker==enabled
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
