version: '3.3'
services:
  db-karam:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: karamdb
      MYSQL_PASSWORD: 9wVC&uoH5Y@dcL
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_USER: karamuser
    volumes:
     - /swarm/data/wordpress-karam/db:/var/lib/mysql
     - /etc/localtime:/etc/localtime:ro
    networks:
     - internal
    logging:
      driver: json-file
  wordpress-karam:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db-karam
      WORDPRESS_DB_NAME: karamdb
      WORDPRESS_DB_PASSWORD: 9wVC&uoH5Y@dcL
      WORDPRESS_DB_USER: karamuser
    volumes:
     - /swarm/data/wordpress-karam/wordpress:/var/www/html
     - /etc/localtime:/etc/localtime:ro
    networks:
     - traefik-public
     - internal
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.wordpress-karam-http.entrypoints: http
        traefik.http.services.wordpress-karam.loadbalancer.server.port: '80'
        traefik.http.routers.wordpress-karam-http.middlewares: https-redirect
        traefik.http.routers.wordpress-karam-https.entrypoints: https
        traefik.http.routers.wordpress-karam-http.rule: Host(`karam.vnerd.nl`)
        traefik.constraint-label: traefik-public
        traefik.http.routers.wordpress-karam-https.rule: Host(`karam.vnerd.nl`)
        traefik.http.routers.wordpress-karam-https.tls.certresolver: le
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.wordpress-karam-https.tls: 'true'
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
