version: '3.3'
services:
  logspout:
    image: gliderlabs/logspout
    command:
     - syslog+tcp://10.10.10.200:2255
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
      replicas: 0
        constraints:
         - node.labels.Arch != i686
