version: '3.3'
services:
  notifiarr:
    image: golift/notifiarr:latest
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - /swarm/config/notifiarr:/config
     - /var/run/utmp:/var/run/utmp
     - /etc/machine-id:/etc/machine-id
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.notifiarr-https.tls: 'true'
        traefik.http.routers.notifiarr-https.tls.certresolver: le
        traefik.http.routers.notifiarr-http.entrypoints: http
        traefik.http.routers.notifiarr-http.rule: Host(`notifiarr.vnerd.nl`)
        traefik.http.services.notifiarr.loadbalancer.server.port: '5454'
        traefik.constraint-label: traefik-public
        traefik.http.routers.notifiarr-https.rule: Host(`notifiarr.vnerd.nl`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.notifiarr-http.middlewares: https-redirect
        traefik.http.routers.notifiarr-https.entrypoints: https
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  traefik-public:
    external: true
