version: '3.3'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - /swarm/data/vaultwarden:/data/
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.vaultwarden-http.middlewares: https-redirect
        traefik.http.routers.vaultwarden-https.entrypoints: https
        traefik.http.routers.vaultwarden-https.tls.certresolver: le
        traefik.http.routers.vaultwarden-https.rule: Host(`password.vnerd.nl`)
        traefik.http.routers.vaultwarden-http.entrypoints: http
        traefik.http.routers.vaultwarden-http.rule: Host(`password.vnerd.nl`)
        traefik.constraint-label: traefik-public
        traefik.http.routers.vaultwarden-https.tls: 'true'
        traefik.http.services.vaultwarden.loadbalancer.server.port: '80'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
