version: '3.3'
services:
  scripts:
    image: nginx:latest
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - /swarm/config/scripts/listFiles.conf:/etc/nginx/conf.d/default.conf
     - /swarm/data/scripts:/usr/share/nginx/html
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.scripts-http.middlewares: https-redirect
        # traefik.http.routers.scripts-https.middlewares: 500error@file
        traefik.http.routers.scripts-http.entrypoints: http
        traefik.http.services.scripts.loadbalancer.server.port: '80'
        traefik.http.routers.scripts-https.tls.certresolver: le
        traefik.constraint-label: traefik-public
        traefik.http.routers.scripts-https.entrypoints: https
        traefik.http.routers.scripts-http.rule: Host(`scripts.vnerd.nl`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.scripts-https.tls: 'true'
        traefik.http.routers.scripts-https.rule: Host(`scripts.vnerd.nl`)
      placement:
        constraints:
         - node.labels.Arch!=i686
networks:
  traefik-public:
    external: true