version: '3.3'
services:
  agent:
    image: swarmpit/agent:2.2
    environment:
      DOCKER_API_VERSION: '1.35'
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - swarmpit-network
    logging:
      driver: json-file
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      restart_policy:
        condition: none
      placement:
        constraints:
         - node.labels.Arch!=i686
  app:
    image: swarmpit/swarmpit:1.9
    environment:
      PGID: '999'
      PUID: '911'
      SWARMPIT_DB: http://db:5984
      SWARMPIT_INFLUXDB: http://influxdb:8086
      TZ: Europe/Amsterdam
    ports:
     - 888:8080
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /nfs-nas-swarm/config/swarmpit:/swarmpit-config
    networks:
     - swarmpit-network
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.swarmpit-https.entrypoints: https
        traefik.http.routers.swarmpit-https.tls.certresolver: le
        traefik.http.routers.swarmpit-http.rule: Host(`swarmpit.vnerd.nl`)
        traefik.http.routers.swarmpit-http.middlewares: https-redirect
        traefik.http.services.swarmpit.loadbalancer.server.port: '8080'
        traefik.http.routers.swarmpit-http.entrypoints: http
        traefik.constraint-label: traefik-public
        traefik.http.routers.swarmpit-https.rule: Host(`swarmpit.vnerd.nl`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.swarmpit-https.tls: 'true'
        traefik.http.routers.swarmpit-https.middlewares: authelia
      placement:
        constraints:
         - node.role == manager
         - node.labels.worker==enabled
  db:
    image: couchdb:2.3.0
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - /nfs-nas-swarm/data/swarmpit/db-data:/opt/couchdb/data
    networks:
     - swarmpit-network
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role==manager
         - node.labels.worker==enabled
      resources:
        reservations:
          cpus: '0.15'
          memory: 128M
        limits:
          cpus: '0.3'
          memory: 256M
  influxdb:
    image: influxdb:1.7
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - /nfs-nas-swarm/data/swarmpit/influx-data:/var/lib/influxdb
    networks:
     - swarmpit-network
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role==manager
         - node.labels.worker==enabled
      resources:
        reservations:
          cpus: '0.3'
          memory: 128M
        limits:
          cpus: '0.6'
          memory: 512M
networks:
  swarmpit-network:
    driver: overlay
  traefik-public:
    external: true
