version: '3.3'
services:
  alertmanager:
    image: stefanprodan/swarmprom-alertmanager:latest
    command:
     - --config.file=/etc/alertmanager/alertmanager.yml
     - --storage.path=/alertmanager
    environment:
      SLACK_CHANNEL: general
      SLACK_URL: https://hooks.slack.com/services/TOKEN
      SLACK_USER: alertmanager
    volumes:
     - /nfs-nas-swarm/config/swarmprom/alertmanager:/alertmanager
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.swarmprom-alertmanager-http.middlewares: https-redirect
        traefik.http.routers.swarmprom-alertmanager-https.entrypoints: https
        traefik.http.routers.swarmprom-alertmanager-https.rule: Host(`alertmanager.swarmprom.vnerd.nl`)
        traefik.http.routers.swarmprom-alertmanager-https.tls: 'true'
        traefik.http.routers.swarmprom-alertmanager-https.middlewares: authelia
        traefik.http.routers.swarmprom-alertmanager-https.tls.certresolver: le
        traefik.http.routers.swarmprom-alertmanager-http.rule: Host(`alertmanager.swarmprom.vnerd.nl`)
        traefik.constraint-label: traefik-public
        traefik.http.routers.swarmprom-alertmanager-http.entrypoints: http
        traefik.http.services.swarmprom-alertmanager.loadbalancer.server.port: '9093'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.labels.Arch!=i686
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    command:
     - -logtostderr
     - -docker_only
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /:/rootfs:ro
     - /var/run:/var/run
     - /sys:/sys:ro
     - /var/lib/docker/:/var/lib/docker:ro
    networks:
     - internal
    logging:
      driver: json-file
    deploy:
      mode: global
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.Arch!=aarch64
  dockerd-exporter:
    image: stefanprodan/caddy:latest
    environment:
      DOCKER_GWBRIDGE_IP: 172.18.0.1
    networks:
     - internal
    logging:
      driver: json-file
    deploy:
      mode: global
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.Arch!=aarch64
  grafana:
    image: stefanprodan/swarmprom-grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: GF_SECURITY_ADMIN_PASSWORD
      GF_SECURITY_ADMIN_USER: admin
      GF_USERS_ALLOW_SIGN_UP: 'false'
    secrets:
      - GF_SECURITY_ADMIN_PASSWORD
    volumes:
     - /nfs-nas-swarm/config/swarmprom/grafana:/var/lib/grafana
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.swarmprom-grafana-http.rule: Host(`grafana.swarmprom.vnerd.nl`)
        traefik.http.routers.swarmprom-grafana-https.middlewares: authelia
        traefik.http.routers.swarmprom-grafana-https.rule: Host(`grafana.swarmprom.vnerd.nl`)
        traefik.http.routers.swarmprom-grafana-http.entrypoints: http
        traefik.http.routers.swarmprom-grafana-https.tls: 'true'
        traefik.http.routers.swarmprom-grafana-https.entrypoints: https
        traefik.constraint-label: traefik-public
        traefik.http.routers.swarmprom-grafana-https.tls.certresolver: le
        traefik.http.routers.swarmprom-grafana-http.middlewares: https-redirect
        traefik.http.services.swarmprom-grafana.loadbalancer.server.port: '3000'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.labels.Arch!=i686
  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.16.0
    command:
     - --path.sysfs=/host/sys
     - --path.procfs=/host/proc
     - --collector.textfile.directory=/etc/node-exporter/
     - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    environment:
      NODE_ID: '{{.Node.ID}}'
    volumes:
     - /proc:/host/proc:ro
     - /sys:/host/sys:ro
     - /:/rootfs:ro
     - /etc/hostname:/etc/nodename
    networks:
     - internal
    logging:
      driver: json-file
    deploy:
      mode: global
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.Arch!=aarch64
  prometheus:
    image: stefanprodan/swarmprom-prometheus:latest
    volumes:
     - /nfs-nas-swarm/config/swarmprom/prometheus:/prometheus
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.swarmprom-prometheus-http.middlewares: https-redirect
        traefik.http.services.swarmprom-prometheus.loadbalancer.server.port: '9090'
        traefik.http.routers.swarmprom-prometheus-https.middlewares: authelia
        traefik.http.routers.swarmprom-prometheus-http.rule: Host(`prometheus.swarmprom.vnerd.nl`)
        traefik.http.routers.swarmprom-prometheus-https.tls.certresolver: le
        traefik.http.routers.swarmprom-prometheus-https.tls: 'true'
        traefik.http.routers.swarmprom-prometheus-http.entrypoints: http
        traefik.constraint-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.swarmprom-prometheus-https.rule: Host(`prometheus.swarmprom.vnerd.nl`)
        traefik.http.routers.swarmprom-prometheus-https.entrypoints: https
      placement:
        constraints:
         - node.labels.Arch!=i686
  unsee:
    image: cloudflare/unsee:v0.8.0
    environment:
      ALERTMANAGER_URIS: default:http://alertmanager:9093
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.swarmprom-unsee-https.middlewares: authelia
        traefik.http.routers.swarmprom-unsee-https.entrypoints: https
        traefik.http.routers.swarmprom-unsee-https.tls: 'true'
        traefik.http.routers.swarmprom-unsee-http.rule: Host(`unsee.swarmprom.vnerd.nl`)
        traefik.http.routers.swarmprom-unsee-https.rule: Host(`unsee.swarmprom.vnerd.nl`)
        traefik.http.routers.swarmprom-unsee-https.tls.certresolver: le
        traefik.http.routers.swarmprom-unsee-http.middlewares: https-redirect
        traefik.constraint-label: traefik-public
        traefik.http.services.swarmprom-unsee.loadbalancer.server.port: '8080'
        traefik.http.routers.swarmprom-unsee-http.entrypoints: http
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.labels.Arch!=i686
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
secrets:
   GF_SECURITY_ADMIN_PASSWORD:
     external: true