version: '3.3'
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:14.3.32
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    ports:
     - 3022:3022
     - 3023:3023
     - 3028:3028
     - 3080:3080
    volumes:
     - /swarm/data/teleport:/var/lib/teleport
     - /swarm/config/teleport:/etc/teleport
    networks:
     - librenms_internal
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.teleport-https.tls.certresolver: le
        traefik.http.routers.teleport-https.entrypoints: https
        traefik.http.services.teleport.loadbalancer.server.port: '3080'
        traefik.http.routers.teleport-http.middlewares: https-redirect
        traefik.http.services.teleport.loadbalancer.server.scheme: https
        traefik.http.routers.teleport-https.tls: 'true'
        traefik.http.routers.teleport-http.entrypoints: http
        traefik.http.routers.teleport-http.rule: Host(`teleport.vnerd.nl`)
        traefik.constraint-label: traefik-public
        traefik.http.routers.teleport-https.rule: Host(`teleport.vnerd.nl`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  internal:
    driver: overlay
  librenms_internal:
    external: true
  traefik-public:
    external: true
