version: '3.3'
services:
  terraform:
    image: hashicorp/terraform:latest
    command:
     - plan
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 0
      placement:
        constraints:
         - node.labels.Arch!=i686
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
