version: '3.4'
services:
  terraform:
    image: debian:trixie-slim
    command: /run/install.sh
    # command: tail -f /dev/null
    # entrypoint: /home/tf01/install.sh
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
    ## a volume to store the initial script to install terraform
     - /swarm/config/terraform/install.sh:/run/install.sh
     ## a volume to store local terraform files
     - /nfs-nas-swarm/config/terraform/vnerd-agents-pool:/home/vnerd-agents-pool
     ## test files
     - /swarm/config/terraform/tf01:/home/tf01
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 0
      placement:
       constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
  terraform-agent01:
    image: hashicorp/tfc-agent:latest
    command: /run/configure.sh
    environment:
      TFC_AGENT_TOKEN: $AGENT_TOKEN
      TFC_AGENT_NAME: 'agent01'
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
    ## a volume to store the script to configure terraform agent
     - /swarm/config/terraform/configure.sh:/run/configure.sh
     ## a volume to store local terraform files
     - /swarm/config/terraform/vnerd-agents-pool:/home/vnerd-agents-pool
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 0
      placement:
       constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  traefik-public:
    external: true