version: '3.8'
services:
  tools:
    image: corentinth/it-tools:latest
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    deploy:
      # replicas: 0
      labels:
        # sablier.enable: 'true'
        traefik.http.routers.tools-https.tls: 'true'
        traefik.http.routers.tools-https.tls.certresolver: le
        traefik.http.routers.tools-http.entrypoints: http
        traefik.http.services.tools.loadbalancer.server.port: '80'
        # traefik.http.routers.tools-https.middlewares: tools-sablier@file
        # traefik.http.routers.tools-https.middlewares: 500error@file
        traefik.http.routers.tools-https.entrypoints: https
        traefik.http.routers.tools-https.rule: Host(`tools.vnerd.nl`)
        # sablier.group: tools
        traefik.constraint-label: traefik-public
        # traefik.docker.lbswarm: 'true'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.tools-http.middlewares: https-redirect
        traefik.http.routers.tools-http.rule: Host(`tools.vnerd.nl`)
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
    