version: '3.3'
services:
  winxp1:
    image: dockurr/windows
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
      VERSION: "winxp"
      # DEVICE_NAME: '/dev/kvm'
      KVM: "N"
    # volumes:
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    # ports:
    #   - 8006:8006
    #   - 3390:3389/tcp
    #   - 3390:3389/udp
    cap_add:
      - NET_ADMIN
    # devices:
      # - /dev/kvm:/dev/kvm
    deploy:
      labels:
        traefik.http.routers.windows-http.rule: Host(`winxp1.vnerd.nl`)
        traefik.http.routers.windows-https.tls.certresolver: le
        traefik.http.routers.windows-https.tls: 'true'
        traefik.http.services.windows.loadbalancer.server.port: '8006'
        traefik.http.routers.windows-http.middlewares: https-redirect
        traefik.http.routers.windows-https.entrypoints: https
        traefik.http.routers.windows-https.rule: Host(`winxp1.vnerd.nl`)
        traefik.constrwindowsnt-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.windows-http.entrypoints: http
        traefik.http.routers.windows-https.middlewares: authelia
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
  winxp2:
    image: dockurr/windows
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
      VERSION: "winxp"
      DEVICE_NAME=/dev/kvm
      # KVM: "N"
    # volumes:
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    # ports:
    #   - 8006:8006
    #   - 3390:3389/tcp
    #   - 3390:3389/udp
    cap_add:
      - NET_ADMIN
    # devices:
      # - /dev/kvm:/dev/kvm
    deploy:
      labels:
        traefik.http.routers.windows-http.rule: Host(`winxp2.vnerd.nl`)
        traefik.http.routers.windows-https.tls.certresolver: le
        traefik.http.routers.windows-https.tls: 'true'
        traefik.http.services.windows.loadbalancer.server.port: '8006'
        traefik.http.routers.windows-http.middlewares: https-redirect
        traefik.http.routers.windows-https.entrypoints: https
        traefik.http.routers.windows-https.rule: Host(`winxp2.vnerd.nl`)
        traefik.constrwindowsnt-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.windows-http.entrypoints: http
        traefik.http.routers.windows-https.middlewares: authelia
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true