version: '3.3'
services:
  winxp1:
    image: dockurr/windows
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
      VERSION: "winxp"
      # DEVICE_NAME: '/dev/kvm'
      # KVM: "N"
    volumes:
    - /nfs-nas-swarm/data/windows/winxp1:/storage
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    # ports:
    #   # - 8006:8006
    #   - 3390:3389/tcp
    #   - 3390:3389/udp
    cap_add:
      - NET_ADMIN
    # devices:
      # - /dev/kvm:/dev/kvm
    deploy:
      replicas: 0
      labels:
        traefik.http.routers.winxp1-http.rule: Host(`winxp1.vnerd.nl`)
        traefik.http.routers.winxp1-https.tls.certresolver: le
        traefik.http.routers.winxp1-https.tls: 'true'
        traefik.http.services.winxp1.loadbalancer.server.port: '8006'
        traefik.http.routers.winxp1-http.middlewares: https-redirect
        traefik.http.routers.winxp1-https.entrypoints: https
        traefik.http.routers.winxp1-https.rule: Host(`winxp1.vnerd.nl`)
        traefik.constraint-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.winxp1-http.entrypoints: http
        traefik.http.routers.winxp1-https.middlewares: authelia
        sablier.enable: 'true'
        sablier.group: windows
        traefik.docker.lbswarm: 'true'
        traefik.http.routers.winxp1-https.middlewares: windows_winxp1-sablier@file
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
  # winxp2:
  #   image: dockurr/windows
  #   environment:
  #     PGID: '911'
  #     PUID: '911'
  #     TZ: Europe/Amsterdam
  #     VERSION: "winxp"
  #     # DEVICE_NAME: '/dev/kvm'
  #     # KVM: "N"
  #   volumes:
  #   - /nfs-nas-swarm/data/windows/winxp2:/storage
  #   networks:
  #    - internal
  #    - traefik-public
  #   logging:
  #     driver: json-file
  #   # ports:
  #   #   - 8006:8006
  #   #   - 3390:3389/tcp
  #   #   - 3390:3389/udp
  #   cap_add:
  #     - NET_ADMIN
  #   # devices:
  #   #   - /dev/kvm:/dev/kvm
  #   deploy:
  #     replicas: 0
  #     labels:
  #       traefik.http.routers.winxp2-http.rule: Host(`winxp2.vnerd.nl`)
  #       traefik.http.routers.winxp2-https.tls.certresolver: le
  #       traefik.http.routers.winxp2-https.tls: 'true'
  #       traefik.http.services.winxp2.loadbalancer.server.port: '8006'
  #       traefik.http.routers.winxp2-http.middlewares: https-redirect
  #       traefik.http.routers.winxp2-https.entrypoints: https
  #       traefik.http.routers.winxp2-https.rule: Host(`winxp2.vnerd.nl`)
  #       traefik.constraint-label: traefik-public
  #       traefik.docker.network: traefik-public
  #       traefik.enable: 'true'
  #       traefik.http.routers.winxp2-http.entrypoints: http
  #       traefik.http.routers.winxp2-https.middlewares: authelia
  #       sablier.enable: 'true'
  #       sablier.group: windows
  #       traefik.docker.lbswarm: 'true'
  #       traefik.http.routers.winxp2-https.middlewares: windows_winxp2-sablier@file
  #     placement:
  #       constraints:
  #        - node.labels.Arch!=i686
  #        - node.labels.worker==enabled
  macos1:
    image: dockurr/macos
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
      VERSION: "ventura"
      # DEVICE_NAME: '/dev/kvm'
      # KVM: "N"
    volumes:
    - /nfs-nas-swarm/data/windows/macos1:/storage
    networks:
     - internal
     - traefik-public
    logging:
      driver: json-file
    # ports:
    #   # - 8006:8006
    #   - 5900:5900/tcp
    #   - 5900:5900/udp
    cap_add:
      - NET_ADMIN
    # devices:
      # - /dev/kvm:/dev/kvm
    deploy:
      replicas: 1
      labels:
        traefik.http.routers.macos1-http.rule: Host(`macos1.vnerd.nl`)
        traefik.http.routers.macos1-https.tls.certresolver: le
        traefik.http.routers.macos1-https.tls: 'true'
        traefik.http.services.macos1.loadbalancer.server.port: '8006'
        traefik.http.routers.macos1-http.middlewares: https-redirect
        traefik.http.routers.macos1-https.entrypoints: https
        traefik.http.routers.macos1-https.rule: Host(`macos1.vnerd.nl`)
        traefik.constraint-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.macos1-http.entrypoints: http
        traefik.http.routers.macos1-https.middlewares: authelia
      placement:
        constraints:
         - node.labels.Arch!=i686
         - node.labels.worker==enabled
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true